/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesUiConceptsRouteImport } from './routes/services.ui-concepts'
import { Route as ServicesLoginPagesRouteImport } from './routes/services.login-pages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUiConceptsRoute = ServicesUiConceptsRouteImport.update({
  id: '/services/ui-concepts',
  path: '/services/ui-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLoginPagesRoute = ServicesLoginPagesRouteImport.update({
  id: '/services/login-pages',
  path: '/services/login-pages',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services/login-pages': typeof ServicesLoginPagesRoute
  '/services/ui-concepts': typeof ServicesUiConceptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/login-pages': typeof ServicesLoginPagesRoute
  '/services/ui-concepts': typeof ServicesUiConceptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services/login-pages': typeof ServicesLoginPagesRoute
  '/services/ui-concepts': typeof ServicesUiConceptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/services/login-pages' | '/services/ui-concepts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/services/login-pages' | '/services/ui-concepts'
  id: '__root__' | '/' | '/services/login-pages' | '/services/ui-concepts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesLoginPagesRoute: typeof ServicesLoginPagesRoute
  ServicesUiConceptsRoute: typeof ServicesUiConceptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ui-concepts': {
      id: '/services/ui-concepts'
      path: '/services/ui-concepts'
      fullPath: '/services/ui-concepts'
      preLoaderRoute: typeof ServicesUiConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/login-pages': {
      id: '/services/login-pages'
      path: '/services/login-pages'
      fullPath: '/services/login-pages'
      preLoaderRoute: typeof ServicesLoginPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesLoginPagesRoute: ServicesLoginPagesRoute,
  ServicesUiConceptsRoute: ServicesUiConceptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
